/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as DiscoveryIndexRouteImport } from './routes/discovery.index'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryIndexRoute = DiscoveryIndexRouteImport.update({
  id: '/discovery/',
  path: '/discovery/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/discovery/': typeof DiscoveryIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/discovery': typeof DiscoveryIndexRoute
  '/review': typeof ReviewIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sources': typeof SourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/discovery/': typeof DiscoveryIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sources/$sourceId'
    | '/discovery/'
    | '/review/'
    | '/settings/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sources/$sourceId'
    | '/discovery'
    | '/review'
    | '/settings'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/sources/$sourceId'
    | '/discovery/'
    | '/review/'
    | '/settings/'
    | '/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  DiscoveryIndexRoute: typeof DiscoveryIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/': {
      id: '/discovery/'
      path: '/discovery'
      fullPath: '/discovery/'
      preLoaderRoute: typeof DiscoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  DiscoveryIndexRoute: DiscoveryIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
